### PR TITLE
feat: add zio-cache quickstart

### PR DESCRIPTION
**Pull request by GrigoriiBerezin**

### CODE REVIEW

**Review by khajavi — APPROVED** [review]

**Comment by GrigoriiBerezin** [comment]
@khajavi you forgot to push it into master, just noticed 😄

**Comment by khajavi** [comment]
@GrigoriiBerezin Can you please resolve the conflicts?

**Comment by GrigoriiBerezin** [comment]
Oh, sorry, didn't see that, have fixed now

**Comment by khajavi** [comment]
@GrigoriiBerezin No problem! Thank you!

**Pull request merged**
