### PR TITLE
Quickstart for zio sql

### PR DESCRIPTION
**Pull request by GrigoriiBerezin**

### CODE REVIEW

**Comment by GrigoriiBerezin** [comment]
Just noticed that tests don't work for all projects except encode-decode-json. Can we somehow fix it by zio-sbt-ci?

**Comment by GrigoriiBerezin** [comment]
@khajavi finally deal with zio sbt plugin and include all tests from needed modules

**Comment by khajavi** [comment]
@GrigoriiBerezin 
Can you please update the PR and remove any links to external images? It's better to use a random UUID for each image.

**Comment by GrigoriiBerezin** [comment]
Ok, will remove links. And what did you mean by "use a random UUID" for each image? Just insert rows in spec instead of migration script?

**Comment by khajavi** [comment]
> Ok, will remove links. And what did you mean by "use a random UUID" for each image?

I meant it is not necessary to have real image data, you can use UUID for each image instead of external URLs.

> Just insert rows in spec instead of migration script?
No problem with the migration script. So let's keep it.

**Comment by GrigoriiBerezin** [comment]
Sorry for long wait, removed real image urls

**Comment by khajavi** [comment]
@GrigoriiBerezin 
Good to merge after fixing the merge conflict.

**Comment by GrigoriiBerezin** [comment]
Will fix links in readme in next quickstarts

**Pull request merged**
