### PR TITLE
upgrade zio version, zio-http version and migrate from zhttp to zio-http

### PR DESCRIPTION
**Pull request by singularityDLW**
`zip-quickstart-hello-world`:

-  upgrade zio version from 2.0.13 to 2.0.15

`zio-quickstart-restful-webservice` series projects:

- migrate to zio-http from zhttp
- upgrade zio-http version to 3.0.0-RC2
- upgrade zio-quill version to 4.6.0

### CODE REVIEW

**Comment by singularityDLW** [comment]
Hi @khajavi, could you please help to review my PR? Thanks so much

**Review by khajavi — APPROVED** [review]

**Comment by khajavi** [comment]
@singularityDLW Thank you! :heart:

**Comment by khajavi** [comment]
Good to merge after CI passes.

**Comment by singularityDLW** [comment]
Hi @khajavi , Sorry I missed some fmt issue before, I fixed them now, Please review this PR and workflow again. Thanks so much for your time.

**Comment by khajavi** [comment]
Hi @singularityDLW 
Thanks again! Thanks for your contribution.

**Pull request merged**
