### PR TITLE
Fix - User has incorrect rights : updated github links

### PR DESCRIPTION
**Pull request by Yummy-Yums**

### CODE REVIEW

**Comment by Yummy-Yums** [comment]
@khajavi the README.md in the restful-webservice , won't it be best to just tell the user to run sbt run in any respective folder they intend to use, rather than have 2 separate sections?

**Comment by khajavi** [comment]
@Yummy-Yums 
What do you mean by having two separate sections?

**Comment by Yummy-Yums** [comment]
> @Yummy-Yums What do you mean by having two separate sections?

the info in both READMEs can be consolidated in one in the main README unless it serves a purpose to be distinct, is it clear?

**Comment by khajavi** [comment]
I agree! Would you like to submit another pull request for it? @Yummy-Yums

**Pull request merged**
